
# This file is automatically generated by setup.py
short_version = '3.0.3'
version = '3.0.3'
full_version = '3.0.3'
git_revision = 'Unknown'
release = True

if not release:
    version = full_version
